#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

public static class CityVehiclesSetupMenu
{
    const string MenuRoot = "Recomeco/Veículos/";

    [MenuItem(MenuRoot + "Cidade: colisão nos carros estacionados (pasta Vehicles)")]
    static void SetupTrafficInScene()
    {
        var scene = SceneManager.GetActiveScene();
        if (!scene.IsValid() || scene.name != RecomecoSceneNames.Cidade)
        {
            EditorUtility.DisplayDialog("Veículos", "Abra a cena Cidade antes de usar este menu.", "OK");
            return;
        }

        var root = GameObject.Find("Vehicles");
        if (root == null)
        {
            EditorUtility.DisplayDialog("Veículos", "Objeto \"Vehicles\" não encontrado na cena.", "OK");
            return;
        }

        var colliders = 0;
        var stripped = 0;
        foreach (Transform child in root.transform)
        {
            if (child.GetComponent<PlayerDrivableVehicle>() != null)
                continue;

            var go = child.gameObject;
            var follower = go.GetComponent<TrafficRouteFollower>();
            if (follower != null)
                Undo.DestroyObjectImmediate(follower);
            var wander = go.GetComponent<CityTrafficVehicle>();
            if (wander != null)
                Undo.DestroyObjectImmediate(wander);

            if (!VehicleColliderUtility.HasExteriorVehicleBounds(go))
            {
                VehicleColliderUtility.RemoveAutogeneratedPhysics(go);
                stripped++;
                continue;
            }

            if (go.GetComponent<ParkedVehicleMarker>() == null)
                Undo.AddComponent<ParkedVehicleMarker>(go);

            VehicleColliderUtility.PrepareParkedObject(go);
            colliders++;
        }

        EditorSceneManager.MarkSceneDirty(scene);
        EditorUtility.DisplayDialog("Veículos",
            colliders + " carro(s) estacionado(s) com colisão.\n" +
            stripped + " prop(s) pequeno(s) sem collider (interior/props).\n\n" +
            "Tráfego em movimento: spawn automático em «ActiveCityTraffic» ao dar Play.\n" +
            "Se houver carros parados no meio da rua: Recomeco → Cidade → Desativar carros decorativos em cima das rotas.\n\nSalve a cena (Ctrl+S).",
            "OK");
    }

    [MenuItem(MenuRoot + "Marcar seleção como estacionado (sem tráfego)")]
    static void MarkParked()
    {
        foreach (var go in Selection.gameObjects)
        {
            if (go.GetComponent<ParkedVehicleMarker>() == null)
                Undo.AddComponent<ParkedVehicleMarker>(go);
        }
    }

    [MenuItem(MenuRoot + "Criar veículo dirigível (prefab na seleção ou na cena)")]
    static void CreateDrivableVehicle()
    {
        GameObject target = Selection.activeGameObject;
        if (target == null)
        {
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(
                "Assets/Flat_Style_Vehicles/Prefabs/Vehicles_interior/vehicle10_interior_1.prefab");
            if (prefab == null)
            {
                EditorUtility.DisplayDialog("Veículos", "Selecione um carro na Hierarchy ou confira o prefab padrão.", "OK");
                return;
            }

            target = PrefabUtility.InstantiatePrefab(prefab) as GameObject;
            Undo.RegisterCreatedObjectUndo(target, "Create drivable vehicle");
            target.name = "Veiculo_Jogador";
        }

        if (target.GetComponent<PlayerDrivableVehicle>() == null)
            Undo.AddComponent<PlayerDrivableVehicle>(target);

        VehicleColliderUtility.EnsureRootBoxCollider(target);
        VehicleColliderUtility.EnsureDrivingRigidbody(target);

        Selection.activeGameObject = target;
        EditorGUIUtility.PingObject(target);
        EditorUtility.DisplayDialog("Veículos",
            "Veículo pronto. Aproxime-se e aperte E para entrar.\n(E de novo, quase parado, para sair.)",
            "OK");
    }
}
#endif
