using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.SceneManagement;

[DisallowMultipleComponent]
public class CityTrafficManager : MonoBehaviour
{
    public static CityTrafficManager Instance { get; private set; }

    const string VehiclesRootName = "Vehicles";
    const string RoutesRootName = "TrafficRoutes";

    [SerializeField] bool createDefaultRoutesIfMissing = true;

    public int AssignAllTraffic()
    {
        var settings = RecomecoGameplaySettings.Instance;
        if (settings != null && !settings.enableCityTraffic)
            return 0;

        var routes = FindObjectsByType<TrafficRoute>(FindObjectsSortMode.None);
        if (routes.Length == 0 && createDefaultRoutesIfMissing)
            routes = CreateDefaultRoutes();

        TrafficRoute.RealignAllRoutesInScene();
        routes = FindObjectsByType<TrafficRoute>(FindObjectsSortMode.None);
        foreach (var route in routes)
        {
            if (route != null)
                route.EnsureReady();
        }

        routes = routes.Where(r => r != null && r.WaypointCount >= 2).ToArray();
        var skipped = 0;
        routes = routes.Where(r =>
        {
            if (CityTrafficZone.IsPlausibleRoute(r))
                return true;

            skipped++;
            Debug.LogWarning("[Tráfego] Rota ignorada (fora da zona urbana ou waypoints inválidos): " + r.name, r);
            return false;
        }).ToArray();

        if (routes.Length == 0)
        {
            Debug.LogWarning("[Tráfego] Nenhuma rota válida na zona da cidade. Ajuste waypoints perto das ruas ou use Recomeco → Cidade → Recriar rotas.");
            return 0;
        }

        if (skipped > 0)
            Debug.Log("[Tráfego] " + skipped + " rota(s) fora da zona ignorada(s).");

        PrepareSceneVehiclesAsParkedDecor();

        var max = settings != null ? settings.maxTrafficVehicles : 24;
        var spawned = CityTrafficSpawner.SpawnOnRoutes(routes, max);
        if (spawned == 0)
            Debug.LogWarning("[Tráfego] Nenhum carro spawnado. Veja erro acima ou menu Copiar prefabs de tráfego.");

        return spawned;
    }

    static void PrepareSceneVehiclesAsParkedDecor()
    {
        var root = GameObject.Find(VehiclesRootName);
        if (root == null)
            return;

        root.isStatic = false;
        PreserveChildrenWorldPositionWhileZeroingRootY(root.transform);

        foreach (Transform child in root.transform)
        {
            if (child == null)
                continue;

            if (child.GetComponent<PlayerDrivableVehicle>() != null)
                continue;

            VehicleColliderUtility.RemoveAutogeneratedPhysics(child.gameObject);

            if (child.GetComponent<ParkedVehicleMarker>() != null)
                VehicleColliderUtility.PrepareParkedObject(child.gameObject);
        }
    }

    TrafficRoute[] CreateDefaultRoutes()
    {
        var anchor = GameObject.Find("Lojinha");
        var center = anchor != null ? anchor.transform.position : new Vector3(-8f, 0f, -24f);
        center.y = 0f;

        var root = GameObject.Find(RoutesRootName);
        if (root == null)
        {
            root = new GameObject(RoutesRootName);
            SceneManager.MoveGameObjectToScene(root, SceneManager.GetActiveScene());
        }

        var routeA = CreateRoute(root.transform, "Rota_NS_1", center + new Vector3(-6f, 0f, -18f), new[]
        {
            new Vector3(0f, 0f, -14f),
            new Vector3(0f, 0f, -6f),
            new Vector3(0f, 0f, 4f),
            new Vector3(0f, 0f, 14f),
        });

        var routeB = CreateRoute(root.transform, "Rota_EW_1", center + new Vector3(-22f, 0f, -26f), new[]
        {
            new Vector3(6f, 0f, 0f),
            new Vector3(14f, 0f, 0f),
            new Vector3(22f, 0f, 0f),
            new Vector3(30f, 0f, 0f),
        });

        return new[] { routeA, routeB };
    }

    static TrafficRoute CreateRoute(Transform parent, string routeName, Vector3 firstWorld, Vector3[] offsets)
    {
        var routeGo = new GameObject(routeName);
        routeGo.transform.SetParent(parent, false);
        routeGo.transform.position = Vector3.zero;

        var route = routeGo.AddComponent<TrafficRoute>();
        route.loop = true;
        route.speedKmh = 26f;

        var points = new Transform[offsets.Length + 1];
        points[0] = CreateWaypoint(routeGo.transform, "Waypoint_00", firstWorld);
        for (var i = 0; i < offsets.Length; i++)
            points[i + 1] = CreateWaypoint(routeGo.transform, "Waypoint_" + (i + 1).ToString("00"), firstWorld + offsets[i]);

        route.waypoints = points;
        return route;
    }

    static Transform CreateWaypoint(Transform parent, string name, Vector3 worldPos)
    {
        var go = new GameObject(name);
        go.transform.SetParent(parent, true);
        go.transform.position = VehicleGroundSnap.Snap(new Vector3(worldPos.x, 0f, worldPos.z));
        return go.transform;
    }

    static void PreserveChildrenWorldPositionWhileZeroingRootY(Transform root)
    {
        if (root == null)
            return;

        var localPos = root.localPosition;
        if (Mathf.Abs(localPos.y) < 0.05f)
            return;

        var worldPositions = new List<(Transform t, Vector3 pos)>();
        foreach (Transform child in root)
        {
            if (child != null)
                worldPositions.Add((child, child.position));
        }

        localPos.y = 0f;
        root.localPosition = localPos;

        foreach (var (t, pos) in worldPositions)
            t.position = pos;
    }

    public static CityTrafficManager EnsureInstance()
    {
        if (Instance != null)
            return Instance;

        var existing = FindFirstObjectByType<CityTrafficManager>();
        if (existing != null)
        {
            Instance = existing;
            return existing;
        }

        var go = new GameObject("CityTrafficManager");
        Instance = go.AddComponent<CityTrafficManager>();
        return Instance;
    }

    void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;
    }

    void OnDestroy()
    {
        if (Instance == this)
            Instance = null;
    }
}
