using UnityEngine;

public static class VehicleColliderUtility
{
    const float Padding = 0.08f;
    const float MinExteriorExtent = 1.35f;
    const string VehiclesRootName = "Vehicles";

    public static bool EnsureRootBoxCollider(GameObject root)
    {
        if (root == null)
            return false;

        var renderers = root.GetComponentsInChildren<Renderer>(false);
        if (renderers == null || renderers.Length == 0)
            return false;

        var world = renderers[0].bounds;
        for (var i = 1; i < renderers.Length; i++)
            world.Encapsulate(renderers[i].bounds);

        var box = root.GetComponent<BoxCollider>();
        if (box == null)
            box = root.AddComponent<BoxCollider>();

        box.isTrigger = false;
        var localCenter = root.transform.InverseTransformPoint(world.center);
        var localSize = root.transform.InverseTransformVector(world.size);
        box.center = localCenter;
        box.size = new Vector3(
            Mathf.Abs(localSize.x) + Padding,
            Mathf.Abs(localSize.y) + Padding,
            Mathf.Abs(localSize.z) + Padding);

        return true;
    }

    public static bool EnsureDrivingRigidbody(GameObject root, float mass = 950f)
    {
        if (root == null)
            return false;

        var rb = root.GetComponent<Rigidbody>();
        if (rb == null)
            rb = root.AddComponent<Rigidbody>();

        rb.isKinematic = false;
        rb.useGravity = true;
        rb.mass = mass;
        rb.interpolation = RigidbodyInterpolation.Interpolate;
        rb.collisionDetectionMode = CollisionDetectionMode.ContinuousDynamic;
        rb.constraints = RigidbodyConstraints.FreezeRotationX | RigidbodyConstraints.FreezeRotationZ;
        return true;
    }

    public static bool EnsureTrafficRigidbody(GameObject root)
    {
        if (root == null)
            return false;

        var rb = root.GetComponent<Rigidbody>();
        if (rb == null)
            rb = root.AddComponent<Rigidbody>();

        rb.isKinematic = true;
        rb.useGravity = false;
        rb.interpolation = RigidbodyInterpolation.Interpolate;
        rb.collisionDetectionMode = CollisionDetectionMode.ContinuousSpeculative;
        rb.constraints = RigidbodyConstraints.FreezeRotationX | RigidbodyConstraints.FreezeRotationZ;
        return true;
    }

    public static bool HasExteriorVehicleBounds(GameObject root)
    {
        if (root == null)
            return false;

        var renderers = root.GetComponentsInChildren<Renderer>(false);
        if (renderers == null || renderers.Length == 0)
            return false;

        var world = renderers[0].bounds;
        for (var i = 1; i < renderers.Length; i++)
            world.Encapsulate(renderers[i].bounds);

        var size = world.size;
        var extent = Mathf.Max(size.x, size.y, size.z);
        return extent >= MinExteriorExtent;
    }

    public static void PrepareTrafficObject(GameObject root)
    {
        if (root == null)
            return;

        if (!HasExteriorVehicleBounds(root))
        {
            RemoveAutogeneratedPhysics(root);
            return;
        }

        ClearStaticFlagsInHierarchy(root);
        RemoveNestedRigidbodies(root);
        EnsureRootBoxCollider(root);
        EnsureTrafficRigidbody(root);
    }

    public static void PrepareParkedObject(GameObject root)
    {
        if (root == null || !HasExteriorVehicleBounds(root))
        {
            RemoveAutogeneratedPhysics(root);
            return;
        }

        ClearStaticFlagsInHierarchy(root);
        RemoveNestedRigidbodies(root);
        EnsureRootBoxCollider(root);
        EnsureTrafficRigidbody(root);
    }

    public static void RemoveAutogeneratedPhysics(GameObject root)
    {
        if (root == null)
            return;

        if (root.GetComponent<PlayerDrivableVehicle>() != null)
            return;

        DestroyComponentIfPresent<TrafficRouteFollower>(root);
        DestroyComponentIfPresent<CityTrafficVehicle>(root);
        DestroyComponentIfPresent<BoxCollider>(root);
        DestroyComponentIfPresent<Rigidbody>(root);
    }

    static void DestroyComponentIfPresent<T>(GameObject root) where T : Component
    {
        var c = root.GetComponent<T>();
        if (c == null)
            return;

        if (Application.isPlaying)
            Object.Destroy(c);
        else
            Object.DestroyImmediate(c);
    }

    public static Transform ResolveVehicleUnderVehicles(Transform t)
    {
        if (t == null)
            return null;

        var vehicles = GameObject.Find(VehiclesRootName);
        if (vehicles == null)
            return t;

        var root = vehicles.transform;
        var current = t;
        while (current.parent != null && current.parent != root)
            current = current.parent;

        return current;
    }

    public static bool ShouldCameraIgnoreCollider(Collider col)
    {
        if (col == null || col.isTrigger)
            return false;

        var activePool = GameObject.Find("ActiveCityTraffic");
        if (activePool != null && col.transform.IsChildOf(activePool.transform))
            return true;

        var vehicle = ResolveVehicleUnderVehicles(col.transform);
        if (vehicle == null)
            return false;

        var vehiclesRoot = GameObject.Find(VehiclesRootName);
        if (vehiclesRoot == null || vehicle.parent != vehiclesRoot.transform)
            return false;

        if (vehicle.GetComponent<ParkedVehicleMarker>() != null)
            return false;

        if (vehicle.GetComponent<PlayerDrivableVehicle>() != null)
            return false;

        if (!HasExteriorVehicleBounds(vehicle.gameObject))
            return true;

        var follower = vehicle.GetComponent<TrafficRouteFollower>();
        if (follower != null && follower.enabled)
            return true;

        var wander = vehicle.GetComponent<CityTrafficVehicle>();
        if (wander != null && wander.enabled)
            return true;

        return false;
    }

    public static void ClearStaticFlagsInHierarchy(GameObject root)
    {
        if (root == null)
            return;

        foreach (var t in root.GetComponentsInChildren<Transform>(true))
        {
            if (t != null)
                t.gameObject.isStatic = false;
        }
    }

    /// <summary>Rigidbody em filhos impede o pai cinemático de arrastar a malha.</summary>
    public static void RemoveNestedRigidbodies(GameObject root)
    {
        if (root == null)
            return;

        foreach (var rb in root.GetComponentsInChildren<Rigidbody>(true))
        {
            if (rb == null || rb.gameObject == root)
                continue;

            Object.Destroy(rb);
        }
    }
}
